version: "3.8"

services:
  cocostum:
    build: .
    ports:
      - "3000:3000"
    environment:
      VITE_BASE_URL_BACKEND: "https://www.communecter.org"
      VITE_SERVER_URL: "https://www.communecter.org"
      VITE_SLUG: "franceTierslieux"
      SITE_CONFIG_PATH: "./config.prod.json"
    volumes:
      - ./config.prod.json:/app/config.prod.json
      - image-cache:/app/.cache/images

volumes:
  image-cache: