// Entrée design-sync — barrel curée des composants exposés à Claude Design.
// ui/ : star exports (primitives + sous-composants). sections/ : default → named.

export * from "@/components/ui/OptimizedImage";
export * from "@/components/ui/T";
export * from "@/components/ui/accordion";
export * from "@/components/ui/alert-dialog";
export * from "@/components/ui/alert";
export * from "@/components/ui/aspect-ratio";
export * from "@/components/ui/avatar";
export * from "@/components/ui/badge";
export * from "@/components/ui/breadcrumb";
export * from "@/components/ui/button-group";
export * from "@/components/ui/button";
export * from "@/components/ui/calendar";
export * from "@/components/ui/card";
export * from "@/components/ui/carousel";
export * from "@/components/ui/chart";
export * from "@/components/ui/checkbox";
export * from "@/components/ui/collapsible";
export * from "@/components/ui/command";
export * from "@/components/ui/context-menu";
export * from "@/components/ui/datetime-picker";
export * from "@/components/ui/dialog";
export * from "@/components/ui/drawer";
export * from "@/components/ui/dropdown-menu";
export * from "@/components/ui/form";
export * from "@/components/ui/hover-card";
export * from "@/components/ui/icon-or-svg";
export * from "@/components/ui/image-viewer";
export * from "@/components/ui/input-group";
export * from "@/components/ui/input-otp";
export * from "@/components/ui/input";
export * from "@/components/ui/label";
export * from "@/components/ui/menubar";
export * from "@/components/ui/modal";
export * from "@/components/ui/multi-combobox";
export * from "@/components/ui/multiple-selector";
export * from "@/components/ui/navigation-menu";
export * from "@/components/ui/pagination";
export * from "@/components/ui/popover";
export * from "@/components/ui/progress";
export * from "@/components/ui/radio-group";
export * from "@/components/ui/resizable";
export * from "@/components/ui/scroll-area";
export * from "@/components/ui/select-objet";
export * from "@/components/ui/select";
export * from "@/components/ui/separator";
export * from "@/components/ui/sheet";
export * from "@/components/ui/sidebar";
export * from "@/components/ui/skeleton";
export * from "@/components/ui/slider";
export * from "@/components/ui/sonner";
export * from "@/components/ui/spinner";
export * from "@/components/ui/switch";
export * from "@/components/ui/table";
export * from "@/components/ui/tabs";
export * from "@/components/ui/textarea";
export * from "@/components/ui/toggle-group";
export * from "@/components/ui/toggle";
export * from "@/components/ui/tooltip";

export { default as AccordionSection } from "@/components/sections/AccordionSection";
export { default as ActionTiles } from "@/components/sections/ActionTiles";
export { default as BannerSection } from "@/components/sections/BannerSection";
export { default as BlogListSection } from "@/components/sections/BlogListSection";
export { default as BlogPostSection } from "@/components/sections/BlogPostSection";
export { default as BreadcrumbSection } from "@/components/sections/BreadcrumbSection";
export { default as CTASection } from "@/components/sections/CTASection";
export { default as CardsSection } from "@/components/sections/CardsSection";
export { default as CategoriesGridSection } from "@/components/sections/CategoriesGridSection";
export { default as ChartSection } from "@/components/sections/ChartSection";
export { default as ComparisonSection } from "@/components/sections/ComparisonSection";
export { default as ContactFormSection } from "@/components/sections/ContactFormSection";
export { default as ContentSection } from "@/components/sections/ContentSection";
export { default as CookieConsentSection } from "@/components/sections/CookieConsentSection";
export { default as CtaCardGrid } from "@/components/sections/CtaCardGrid";
export { default as CtaNewsletter } from "@/components/sections/CtaNewsletter";
export { default as EventListSection } from "@/components/sections/EventListSection";
export { default as FAQSection } from "@/components/sections/FAQSection";
export { default as FeatureComparisonSection } from "@/components/sections/FeatureComparisonSection";
export { default as FeaturesGlass } from "@/components/sections/FeaturesGlass";
export { default as GallerySection } from "@/components/sections/GallerySection";
export { default as HTMLSection } from "@/components/sections/HTMLSection";
export { default as HeroEntityBanner } from "@/components/sections/HeroEntityBanner";
export { default as HeroParallax } from "@/components/sections/HeroParallax";
export { default as HeroQuickAccess } from "@/components/sections/HeroQuickAccess";
export { default as HeroSection } from "@/components/sections/HeroSection";
export { default as HeroTintedOverlay } from "@/components/sections/HeroTintedOverlay";
export { default as HeroWithIconSection } from "@/components/sections/HeroWithIconSection";
export { default as LogoCloudSection } from "@/components/sections/LogoCloudSection";
export { default as MapSection } from "@/components/sections/MapSection";
export { default as MarkdownSection } from "@/components/sections/MarkdownSection";
export { default as NewsletterSection } from "@/components/sections/NewsletterSection";
export { default as PricingSection } from "@/components/sections/PricingSection";
export { default as ProductShowcaseSection } from "@/components/sections/ProductShowcaseSection";
export { default as SocialFeedSection } from "@/components/sections/SocialFeedSection";
export { default as StatsSection } from "@/components/sections/StatsSection";
export { default as StepsSection } from "@/components/sections/StepsSection";
export { default as TableSection } from "@/components/sections/TableSection";
export { default as TeamSection } from "@/components/sections/TeamSection";
export { default as TestimonialsSection } from "@/components/sections/TestimonialsSection";
export { default as TimelineSection } from "@/components/sections/TimelineSection";
export { default as TitleSection } from "@/components/sections/TitleSection";
export { default as VideoSection } from "@/components/sections/VideoSection";
export { default as MultipleSelector } from "@/components/ui/multiple-selector";
export { toast } from "sonner";

// Extension modules (composants présentationnels props-driven, audit 15/07/2026)
export { default as AmpliHeader } from "@/modules/ampli/components/sections/AmpliHeader";
export { ArticleCard } from "@/modules/blog/components/ArticleCard";
export { ArticleCardCompact } from "@/modules/blog/components/ArticleCardCompact";
export { ArticleCardPoster } from "@/modules/blog/components/ArticleCardPoster";
export { ArticleReader } from "@/modules/blog/components/ArticleReader";
export { ArticleReaderPoster } from "@/modules/blog/components/ArticleReaderPoster";
export { CagnotteAmountPicker } from "@/modules/cagnotte/components/parts/CagnotteAmountPicker";
export { CagnotteMilestoneList } from "@/modules/cagnotte/components/parts/CagnotteMilestoneList";
export { CagnotteProjectProgressCard } from "@/modules/cagnotte/components/parts/CagnotteProjectProgressCard";
export { CagnotteSuccessScreen } from "@/modules/cagnotte/components/parts/CagnotteSuccessScreen";
export { CommentInput } from "@/modules/news/components/comment/CommentInput";
export { CountBadge } from "@/modules/profil/components/shared/CountBadge";
export { EmptyState } from "@/modules/profil/components/shared/EmptyState";
export { EntityCardDetailed } from "@/modules/profil/components/shared/EntityCardDetailed";
export { EntityEmptyState } from "@/modules/profil/components/shared/EntityEmptyState";
export { EntityGrid } from "@/modules/profil/components/shared/EntityGrid";
export { EntityGridView } from "@/modules/profil/components/shared/EntityGridView";
export { FileUploadProgress } from "@/modules/news/components/forms/FileUploadProgress";
export { default as FilterDropdown } from "@/modules/search/components/FilterDropdown";
export { LoadingState } from "@/modules/profil/components/shared/LoadingState";
export { default as MapMarkerAvatar } from "@/modules/search/components/mapMarker/MapMarkerAvatar";
export { default as MapMarkerCircle } from "@/modules/search/components/mapMarker/MapMarkerCircle";
export { default as MapMarkerIcon } from "@/modules/search/components/mapMarker/MapMarkerIcon";
export { default as MapMarkerPin } from "@/modules/search/components/mapMarker/MapMarkerPin";
export { MeeteemFilters } from "@/modules/ampli/components/sections/parts/MeeteemFilters";
export { MilestoneCard } from "@/modules/cagnotte/components/sections/parts/MilestoneCard";
export { NewsFileList } from "@/modules/news/components/media/NewsFileList";
export { NewsImageGrid } from "@/modules/news/components/media/NewsImageGrid";
export { NewsReactionPicker } from "@/modules/news/components/interactions/NewsReactionPicker";
export { default as SearchBubbleChart } from "@/modules/search/components/SearchBubbleChart";
export { default as SearchCardSkeleton } from "@/modules/search/components/SearchCardSkeleton";
export { default as SearchListSkeleton } from "@/modules/search/components/SearchListSkeleton";
export { default as SearchTextInput } from "@/modules/search/components/SearchTextInput";
export { default as SectionTitleTL } from "@/modules/profil/components/sections/custom/SectionTitleTL";

// Chrome de site : headers, footers, primitives partagées (présentationnels,
// header/footer passés en prop — utilities auth/notifications OFF en preview)
export { default as HeaderStandard } from "@/components/layout/header/HeaderStandard";
export { default as HeaderMegaMenu } from "@/components/layout/header/HeaderMegaMenu";
export { default as HeaderTransparentScroll } from "@/components/layout/header/HeaderTransparentScroll";
export { default as HeaderMinimal } from "@/components/layout/header/HeaderMinimal";
export { default as HeaderUnderlineNav } from "@/components/layout/header/HeaderUnderlineNav";
export { default as HeaderTransparentDark } from "@/components/layout/header/HeaderTransparentDark";
export { default as FooterRich } from "@/components/layout/footer/FooterRich";
export { default as FooterMinimalCentered } from "@/components/layout/footer/FooterMinimalCentered";
export { default as FooterSidebarColumns } from "@/components/layout/footer/FooterSidebarColumns";
export { default as FooterContactPartners } from "@/components/layout/footer/FooterContactPartners";
export { default as NavLink } from "@/components/layout/NavLink";
export { default as LangSwitch } from "@/components/layout/header/LangSwitch";
export { default as MobileMenuSheet } from "@/components/layout/header/MobileMenuSheet";
export { default as SocialLinks } from "@/components/layout/footer/SocialLinks";

// i18n des modules embarqués (namespaces requis par les composants cagnotte)
import "@/components/layout/i18n";
import "@/modules/cagnotte/i18n";
import "@/modules/blog/i18n";
import "@/modules/search/i18n";
import "@/modules/profil/i18n";
import "@/modules/news/i18n";
import "@/modules/ampli/i18n";
