/**
 * Liste des pays avec leurs codes ISO 3166-1 alpha-2
 * Utilisé pour les sélecteurs de pays dans les formulaires d'adresse
 */

export interface Country {
  code: string;
  name: string;
  nameFr: string;
}

export const CountryList: Country[] = [
  { code: "FR", name: "France", nameFr: "France" },
  { code: "GP", name: "Guadeloupe", nameFr: "Guadeloupe" },
  { code: "MQ", name: "Martinique", nameFr: "Martinique" },
  { code: "GF", name: "French Guiana", nameFr: "Guyane française" },
  { code: "RE", name: "Réunion", nameFr: "La Réunion" },
  { code: "YT", name: "Mayotte", nameFr: "Mayotte" },
  { code: "PF", name: "French Polynesia", nameFr: "Polynésie française" },
  { code: "BE", name: "Belgium", nameFr: "Belgique" },
  { code: "CH", name: "Switzerland", nameFr: "Suisse" },
  { code: "CA", name: "Canada", nameFr: "Canada" },
  { code: "DE", name: "Germany", nameFr: "Allemagne" },
  { code: "ES", name: "Spain", nameFr: "Espagne" },
  { code: "IT", name: "Italy", nameFr: "Italie" },
  { code: "GB", name: "United Kingdom", nameFr: "Royaume-Uni" },
  { code: "US", name: "United States", nameFr: "États-Unis" },
  { code: "AD", name: "Andorra", nameFr: "Andorre" },
  { code: "AE", name: "United Arab Emirates", nameFr: "Émirats arabes unis" },
  { code: "AF", name: "Afghanistan", nameFr: "Afghanistan" },
  { code: "AG", name: "Antigua and Barbuda", nameFr: "Antigua-et-Barbuda" },
  { code: "AI", name: "Anguilla", nameFr: "Anguilla" },
  { code: "AL", name: "Albania", nameFr: "Albanie" },
  { code: "AM", name: "Armenia", nameFr: "Arménie" },
  { code: "AO", name: "Angola", nameFr: "Angola" },
  { code: "AQ", name: "Antarctica", nameFr: "Antarctique" },
  { code: "AR", name: "Argentina", nameFr: "Argentine" },
  { code: "AS", name: "American Samoa", nameFr: "Samoa américaines" },
  { code: "AT", name: "Austria", nameFr: "Autriche" },
  { code: "AU", name: "Australia", nameFr: "Australie" },
  { code: "AW", name: "Aruba", nameFr: "Aruba" },
  { code: "AX", name: "Åland Islands", nameFr: "Îles Åland" },
  { code: "AZ", name: "Azerbaijan", nameFr: "Azerbaïdjan" },
  { code: "BA", name: "Bosnia and Herzegovina", nameFr: "Bosnie-Herzégovine" },
  { code: "BB", name: "Barbados", nameFr: "Barbade" },
  { code: "BD", name: "Bangladesh", nameFr: "Bangladesh" },
  { code: "BF", name: "Burkina Faso", nameFr: "Burkina Faso" },
  { code: "BG", name: "Bulgaria", nameFr: "Bulgarie" },
  { code: "BH", name: "Bahrain", nameFr: "Bahreïn" },
  { code: "BI", name: "Burundi", nameFr: "Burundi" },
  { code: "BJ", name: "Benin", nameFr: "Bénin" },
  { code: "BL", name: "Saint Barthélemy", nameFr: "Saint-Barthélemy" },
  { code: "BM", name: "Bermuda", nameFr: "Bermudes" },
  { code: "BN", name: "Brunei", nameFr: "Brunei" },
  { code: "BO", name: "Bolivia", nameFr: "Bolivie" },
  { code: "BQ", name: "Caribbean Netherlands", nameFr: "Pays-Bas caribéens" },
  { code: "BR", name: "Brazil", nameFr: "Brésil" },
  { code: "BS", name: "Bahamas", nameFr: "Bahamas" },
  { code: "BT", name: "Bhutan", nameFr: "Bhoutan" },
  { code: "BV", name: "Bouvet Island", nameFr: "Île Bouvet" },
  { code: "BW", name: "Botswana", nameFr: "Botswana" },
  { code: "BY", name: "Belarus", nameFr: "Biélorussie" },
  { code: "BZ", name: "Belize", nameFr: "Belize" },
  { code: "CC", name: "Cocos Islands", nameFr: "Îles Cocos" },
  { code: "CD", name: "DR Congo", nameFr: "RD Congo" },
  { code: "CF", name: "Central African Republic", nameFr: "République centrafricaine" },
  { code: "CG", name: "Republic of the Congo", nameFr: "République du Congo" },
  { code: "CI", name: "Ivory Coast", nameFr: "Côte d'Ivoire" },
  { code: "CK", name: "Cook Islands", nameFr: "Îles Cook" },
  { code: "CL", name: "Chile", nameFr: "Chili" },
  { code: "CM", name: "Cameroon", nameFr: "Cameroun" },
  { code: "CN", name: "China", nameFr: "Chine" },
  { code: "CO", name: "Colombia", nameFr: "Colombie" },
  { code: "CR", name: "Costa Rica", nameFr: "Costa Rica" },
  { code: "CU", name: "Cuba", nameFr: "Cuba" },
  { code: "CV", name: "Cape Verde", nameFr: "Cap-Vert" },
  { code: "CW", name: "Curaçao", nameFr: "Curaçao" },
  { code: "CX", name: "Christmas Island", nameFr: "Île Christmas" },
  { code: "CY", name: "Cyprus", nameFr: "Chypre" },
  { code: "CZ", name: "Czechia", nameFr: "Tchéquie" },
  { code: "DJ", name: "Djibouti", nameFr: "Djibouti" },
  { code: "DK", name: "Denmark", nameFr: "Danemark" },
  { code: "DM", name: "Dominica", nameFr: "Dominique" },
  { code: "DO", name: "Dominican Republic", nameFr: "République dominicaine" },
  { code: "DZ", name: "Algeria", nameFr: "Algérie" },
  { code: "EC", name: "Ecuador", nameFr: "Équateur" },
  { code: "EE", name: "Estonia", nameFr: "Estonie" },
  { code: "EG", name: "Egypt", nameFr: "Égypte" },
  { code: "EH", name: "Western Sahara", nameFr: "Sahara occidental" },
  { code: "ER", name: "Eritrea", nameFr: "Érythrée" },
  { code: "ET", name: "Ethiopia", nameFr: "Éthiopie" },
  { code: "FI", name: "Finland", nameFr: "Finlande" },
  { code: "FJ", name: "Fiji", nameFr: "Fidji" },
  { code: "FK", name: "Falkland Islands", nameFr: "Îles Malouines" },
  { code: "FM", name: "Micronesia", nameFr: "Micronésie" },
  { code: "FO", name: "Faroe Islands", nameFr: "Îles Féroé" },
  { code: "GA", name: "Gabon", nameFr: "Gabon" },
  { code: "GD", name: "Grenada", nameFr: "Grenade" },
  { code: "GE", name: "Georgia", nameFr: "Géorgie" },
  { code: "GG", name: "Guernsey", nameFr: "Guernesey" },
  { code: "GH", name: "Ghana", nameFr: "Ghana" },
  { code: "GI", name: "Gibraltar", nameFr: "Gibraltar" },
  { code: "GL", name: "Greenland", nameFr: "Groenland" },
  { code: "GM", name: "Gambia", nameFr: "Gambie" },
  { code: "GN", name: "Guinea", nameFr: "Guinée" },
  { code: "GQ", name: "Equatorial Guinea", nameFr: "Guinée équatoriale" },
  { code: "GR", name: "Greece", nameFr: "Grèce" },
  { code: "GS", name: "South Georgia", nameFr: "Géorgie du Sud" },
  { code: "GT", name: "Guatemala", nameFr: "Guatemala" },
  { code: "GU", name: "Guam", nameFr: "Guam" },
  { code: "GW", name: "Guinea-Bissau", nameFr: "Guinée-Bissau" },
  { code: "GY", name: "Guyana", nameFr: "Guyana" },
  { code: "HK", name: "Hong Kong", nameFr: "Hong Kong" },
  { code: "HM", name: "Heard Island and McDonald Islands", nameFr: "Îles Heard-et-MacDonald" },
  { code: "HN", name: "Honduras", nameFr: "Honduras" },
  { code: "HR", name: "Croatia", nameFr: "Croatie" },
  { code: "HT", name: "Haiti", nameFr: "Haïti" },
  { code: "HU", name: "Hungary", nameFr: "Hongrie" },
  { code: "ID", name: "Indonesia", nameFr: "Indonésie" },
  { code: "IE", name: "Ireland", nameFr: "Irlande" },
  { code: "IL", name: "Israel", nameFr: "Israël" },
  { code: "IM", name: "Isle of Man", nameFr: "Île de Man" },
  { code: "IN", name: "India", nameFr: "Inde" },
  { code: "IO", name: "British Indian Ocean Territory", nameFr: "Territoire britannique de l'océan Indien" },
  { code: "IQ", name: "Iraq", nameFr: "Irak" },
  { code: "IR", name: "Iran", nameFr: "Iran" },
  { code: "IS", name: "Iceland", nameFr: "Islande" },
  { code: "JE", name: "Jersey", nameFr: "Jersey" },
  { code: "JM", name: "Jamaica", nameFr: "Jamaïque" },
  { code: "JO", name: "Jordan", nameFr: "Jordanie" },
  { code: "JP", name: "Japan", nameFr: "Japon" },
  { code: "KE", name: "Kenya", nameFr: "Kenya" },
  { code: "KG", name: "Kyrgyzstan", nameFr: "Kirghizistan" },
  { code: "KH", name: "Cambodia", nameFr: "Cambodge" },
  { code: "KI", name: "Kiribati", nameFr: "Kiribati" },
  { code: "KM", name: "Comoros", nameFr: "Comores" },
  { code: "KN", name: "Saint Kitts and Nevis", nameFr: "Saint-Christophe-et-Niévès" },
  { code: "KP", name: "North Korea", nameFr: "Corée du Nord" },
  { code: "KR", name: "South Korea", nameFr: "Corée du Sud" },
  { code: "KW", name: "Kuwait", nameFr: "Koweït" },
  { code: "KY", name: "Cayman Islands", nameFr: "Îles Caïmans" },
  { code: "KZ", name: "Kazakhstan", nameFr: "Kazakhstan" },
  { code: "LA", name: "Laos", nameFr: "Laos" },
  { code: "LB", name: "Lebanon", nameFr: "Liban" },
  { code: "LC", name: "Saint Lucia", nameFr: "Sainte-Lucie" },
  { code: "LI", name: "Liechtenstein", nameFr: "Liechtenstein" },
  { code: "LK", name: "Sri Lanka", nameFr: "Sri Lanka" },
  { code: "LR", name: "Liberia", nameFr: "Liberia" },
  { code: "LS", name: "Lesotho", nameFr: "Lesotho" },
  { code: "LT", name: "Lithuania", nameFr: "Lituanie" },
  { code: "LU", name: "Luxembourg", nameFr: "Luxembourg" },
  { code: "LV", name: "Latvia", nameFr: "Lettonie" },
  { code: "LY", name: "Libya", nameFr: "Libye" },
  { code: "MA", name: "Morocco", nameFr: "Maroc" },
  { code: "MC", name: "Monaco", nameFr: "Monaco" },
  { code: "MD", name: "Moldova", nameFr: "Moldavie" },
  { code: "ME", name: "Montenegro", nameFr: "Monténégro" },
  { code: "MF", name: "Saint Martin", nameFr: "Saint-Martin" },
  { code: "MG", name: "Madagascar", nameFr: "Madagascar" },
  { code: "MH", name: "Marshall Islands", nameFr: "Îles Marshall" },
  { code: "MK", name: "North Macedonia", nameFr: "Macédoine du Nord" },
  { code: "ML", name: "Mali", nameFr: "Mali" },
  { code: "MM", name: "Myanmar", nameFr: "Myanmar" },
  { code: "MN", name: "Mongolia", nameFr: "Mongolie" },
  { code: "MO", name: "Macau", nameFr: "Macao" },
  { code: "MP", name: "Northern Mariana Islands", nameFr: "Îles Mariannes du Nord" },
  { code: "MR", name: "Mauritania", nameFr: "Mauritanie" },
  { code: "MS", name: "Montserrat", nameFr: "Montserrat" },
  { code: "MT", name: "Malta", nameFr: "Malte" },
  { code: "MU", name: "Mauritius", nameFr: "Maurice" },
  { code: "MV", name: "Maldives", nameFr: "Maldives" },
  { code: "MW", name: "Malawi", nameFr: "Malawi" },
  { code: "MX", name: "Mexico", nameFr: "Mexique" },
  { code: "MY", name: "Malaysia", nameFr: "Malaisie" },
  { code: "MZ", name: "Mozambique", nameFr: "Mozambique" },
  { code: "NA", name: "Namibia", nameFr: "Namibie" },
  { code: "NC", name: "New Caledonia", nameFr: "Nouvelle-Calédonie" },
  { code: "NE", name: "Niger", nameFr: "Niger" },
  { code: "NF", name: "Norfolk Island", nameFr: "Île Norfolk" },
  { code: "NG", name: "Nigeria", nameFr: "Nigeria" },
  { code: "NI", name: "Nicaragua", nameFr: "Nicaragua" },
  { code: "NL", name: "Netherlands", nameFr: "Pays-Bas" },
  { code: "NO", name: "Norway", nameFr: "Norvège" },
  { code: "NP", name: "Nepal", nameFr: "Népal" },
  { code: "NR", name: "Nauru", nameFr: "Nauru" },
  { code: "NU", name: "Niue", nameFr: "Niue" },
  { code: "NZ", name: "New Zealand", nameFr: "Nouvelle-Zélande" },
  { code: "OM", name: "Oman", nameFr: "Oman" },
  { code: "PA", name: "Panama", nameFr: "Panama" },
  { code: "PE", name: "Peru", nameFr: "Pérou" },
  { code: "PG", name: "Papua New Guinea", nameFr: "Papouasie-Nouvelle-Guinée" },
  { code: "PH", name: "Philippines", nameFr: "Philippines" },
  { code: "PK", name: "Pakistan", nameFr: "Pakistan" },
  { code: "PL", name: "Poland", nameFr: "Pologne" },
  { code: "PM", name: "Saint Pierre and Miquelon", nameFr: "Saint-Pierre-et-Miquelon" },
  { code: "PN", name: "Pitcairn Islands", nameFr: "Îles Pitcairn" },
  { code: "PR", name: "Puerto Rico", nameFr: "Porto Rico" },
  { code: "PS", name: "Palestine", nameFr: "Palestine" },
  { code: "PT", name: "Portugal", nameFr: "Portugal" },
  { code: "PW", name: "Palau", nameFr: "Palaos" },
  { code: "PY", name: "Paraguay", nameFr: "Paraguay" },
  { code: "QA", name: "Qatar", nameFr: "Qatar" },
  { code: "RO", name: "Romania", nameFr: "Roumanie" },
  { code: "RS", name: "Serbia", nameFr: "Serbie" },
  { code: "RU", name: "Russia", nameFr: "Russie" },
  { code: "RW", name: "Rwanda", nameFr: "Rwanda" },
  { code: "SA", name: "Saudi Arabia", nameFr: "Arabie saoudite" },
  { code: "SB", name: "Solomon Islands", nameFr: "Îles Salomon" },
  { code: "SC", name: "Seychelles", nameFr: "Seychelles" },
  { code: "SD", name: "Sudan", nameFr: "Soudan" },
  { code: "SE", name: "Sweden", nameFr: "Suède" },
  { code: "SG", name: "Singapore", nameFr: "Singapour" },
  { code: "SH", name: "Saint Helena", nameFr: "Sainte-Hélène" },
  { code: "SI", name: "Slovenia", nameFr: "Slovénie" },
  { code: "SJ", name: "Svalbard and Jan Mayen", nameFr: "Svalbard et Jan Mayen" },
  { code: "SK", name: "Slovakia", nameFr: "Slovaquie" },
  { code: "SL", name: "Sierra Leone", nameFr: "Sierra Leone" },
  { code: "SM", name: "San Marino", nameFr: "Saint-Marin" },
  { code: "SN", name: "Senegal", nameFr: "Sénégal" },
  { code: "SO", name: "Somalia", nameFr: "Somalie" },
  { code: "SR", name: "Suriname", nameFr: "Suriname" },
  { code: "SS", name: "South Sudan", nameFr: "Soudan du Sud" },
  { code: "ST", name: "São Tomé and Príncipe", nameFr: "Sao Tomé-et-Principe" },
  { code: "SV", name: "El Salvador", nameFr: "Salvador" },
  { code: "SX", name: "Sint Maarten", nameFr: "Saint-Martin (partie néerlandaise)" },
  { code: "SY", name: "Syria", nameFr: "Syrie" },
  { code: "SZ", name: "Eswatini", nameFr: "Eswatini" },
  { code: "TC", name: "Turks and Caicos Islands", nameFr: "Îles Turques-et-Caïques" },
  { code: "TD", name: "Chad", nameFr: "Tchad" },
  { code: "TF", name: "French Southern Territories", nameFr: "Terres australes françaises" },
  { code: "TG", name: "Togo", nameFr: "Togo" },
  { code: "TH", name: "Thailand", nameFr: "Thaïlande" },
  { code: "TJ", name: "Tajikistan", nameFr: "Tadjikistan" },
  { code: "TK", name: "Tokelau", nameFr: "Tokelau" },
  { code: "TL", name: "Timor-Leste", nameFr: "Timor oriental" },
  { code: "TM", name: "Turkmenistan", nameFr: "Turkménistan" },
  { code: "TN", name: "Tunisia", nameFr: "Tunisie" },
  { code: "TO", name: "Tonga", nameFr: "Tonga" },
  { code: "TR", name: "Turkey", nameFr: "Turquie" },
  { code: "TT", name: "Trinidad and Tobago", nameFr: "Trinité-et-Tobago" },
  { code: "TV", name: "Tuvalu", nameFr: "Tuvalu" },
  { code: "TW", name: "Taiwan", nameFr: "Taïwan" },
  { code: "TZ", name: "Tanzania", nameFr: "Tanzanie" },
  { code: "UA", name: "Ukraine", nameFr: "Ukraine" },
  { code: "UG", name: "Uganda", nameFr: "Ouganda" },
  { code: "UM", name: "U.S. Minor Outlying Islands", nameFr: "Îles mineures éloignées des États-Unis" },
  { code: "UY", name: "Uruguay", nameFr: "Uruguay" },
  { code: "UZ", name: "Uzbekistan", nameFr: "Ouzbékistan" },
  { code: "VA", name: "Vatican City", nameFr: "Vatican" },
  { code: "VC", name: "Saint Vincent and the Grenadines", nameFr: "Saint-Vincent-et-les-Grenadines" },
  { code: "VE", name: "Venezuela", nameFr: "Venezuela" },
  { code: "VG", name: "British Virgin Islands", nameFr: "Îles Vierges britanniques" },
  { code: "VI", name: "U.S. Virgin Islands", nameFr: "Îles Vierges des États-Unis" },
  { code: "VN", name: "Vietnam", nameFr: "Viêt Nam" },
  { code: "VU", name: "Vanuatu", nameFr: "Vanuatu" },
  { code: "WF", name: "Wallis and Futuna", nameFr: "Wallis-et-Futuna" },
  { code: "WS", name: "Samoa", nameFr: "Samoa" },
  { code: "XK", name: "Kosovo", nameFr: "Kosovo" },
  { code: "YE", name: "Yemen", nameFr: "Yémen" },
  { code: "ZA", name: "South Africa", nameFr: "Afrique du Sud" },
  { code: "ZM", name: "Zambia", nameFr: "Zambie" },
  { code: "ZW", name: "Zimbabwe", nameFr: "Zimbabwe" },
];

/**
 * Pays où l'API BAN (Base Adresse Nationale) française est disponible
 * Pour ces pays, on peut utiliser l'autocomplétion de rue via api-adresse.data.gouv.fr
 */
export const ISO_COUNTRIES_FR = ["FR", "GP", "MQ", "GF", "RE", "YT", "PF"];
