export interface SectionMeta {
  label: string;
  desc: string;
  image: string;
}

const SECTION_META: Record<string, SectionMeta> = {
  hero: { label: "Hero", desc: "Bannière principale avec titre, sous-titre et CTA", image: "https://placehold.co/300x180/1a1a2e/eee?text=Hero" },
  cards: { label: "Cards", desc: "Grille de cartes avec image, titre et description", image: "https://placehold.co/300x180/2d3436/eee?text=Cards" },
  gallery: { label: "Gallery", desc: "Galerie d'images en grille ou masonry", image: "https://placehold.co/300x180/636e72/eee?text=Gallery" },
  video: { label: "Video", desc: "Lecteur vidéo intégré (YouTube, Vimeo)", image: "https://placehold.co/300x180/0984e3/eee?text=Video" },
  cta: { label: "CTA", desc: "Appel à l'action avec titre et bouton", image: "https://placehold.co/300x180/6c5ce7/eee?text=CTA" },
  faq: { label: "FAQ", desc: "Questions fréquentes en accordéon", image: "https://placehold.co/300x180/00b894/eee?text=FAQ" },
  testimonials: { label: "Testimonials", desc: "Témoignages clients avec photo et citation", image: "https://placehold.co/300x180/fdcb6e/333?text=Testimonials" },
  team: { label: "Team", desc: "Présentation de l'équipe avec photos", image: "https://placehold.co/300x180/e17055/eee?text=Team" },
  stats: { label: "Stats", desc: "Chiffres clés et statistiques", image: "https://placehold.co/300x180/00cec9/eee?text=Stats" },
  pricing: { label: "Pricing", desc: "Tableau de tarifs avec plans", image: "https://placehold.co/300x180/a29bfe/eee?text=Pricing" },
  steps: { label: "Steps", desc: "Étapes numérotées d'un processus", image: "https://placehold.co/300x180/55efc4/333?text=Steps" },
  timeline: { label: "Timeline", desc: "Frise chronologique d'événements", image: "https://placehold.co/300x180/74b9ff/333?text=Timeline" },
  accordion: { label: "Accordion", desc: "Blocs dépliables avec contenu", image: "https://placehold.co/300x180/fab1a0/333?text=Accordion" },
  tabs: { label: "Tabs", desc: "Contenu organisé en onglets", image: "https://placehold.co/300x180/81ecec/333?text=Tabs" },
  table: { label: "Table", desc: "Tableau de données structurées", image: "https://placehold.co/300x180/dfe6e9/333?text=Table" },
  map: { label: "Map", desc: "Carte interactive (Leaflet)", image: "https://placehold.co/300x180/00b894/eee?text=Map" },
  newsletter: { label: "Newsletter", desc: "Formulaire d'inscription email", image: "https://placehold.co/300x180/e84393/eee?text=Newsletter" },
  contactForm: { label: "Contact Form", desc: "Formulaire de contact complet", image: "https://placehold.co/300x180/0984e3/eee?text=Contact+Form" },
  html: { label: "HTML", desc: "Code HTML libre et personnalisé", image: "https://placehold.co/300x180/2d3436/eee?text=HTML" },
  markdown: { label: "Markdown", desc: "Contenu Markdown rendu en HTML", image: "https://placehold.co/300x180/636e72/eee?text=Markdown" },
  banner: { label: "Banner", desc: "Bandeau d'annonce ou promotion", image: "https://placehold.co/300x180/fdcb6e/333?text=Banner" },
  chart: { label: "Chart", desc: "Graphiques et visualisations", image: "https://placehold.co/300x180/6c5ce7/eee?text=Chart" },
  logoCloud: { label: "Logo Cloud", desc: "Logos partenaires ou clients", image: "https://placehold.co/300x180/b2bec3/333?text=Logo+Cloud" },
  comparison: { label: "Comparison", desc: "Tableau comparatif de fonctionnalités", image: "https://placehold.co/300x180/a29bfe/eee?text=Comparison" },
  featureComparison: { label: "Feature Comparison", desc: "Comparaison détaillée de fonctionnalités", image: "https://placehold.co/300x180/74b9ff/333?text=Feature+Comp" },
  title: { label: "Title", desc: "Titre de section simple", image: "https://placehold.co/300x180/dfe6e9/333?text=Title" },
  content: { label: "Content", desc: "Bloc de contenu texte riche", image: "https://placehold.co/300x180/636e72/eee?text=Content" },
  blogList: { label: "Blog List", desc: "Liste d'articles de blog", image: "https://placehold.co/300x180/e17055/eee?text=Blog+List" },
  blogPost: { label: "Blog Post", desc: "Article de blog complet", image: "https://placehold.co/300x180/fab1a0/333?text=Blog+Post" },
  loginForm: { label: "Login Form", desc: "Formulaire de connexion", image: "https://placehold.co/300x180/0984e3/eee?text=Login" },
  registerForm: { label: "Register Form", desc: "Formulaire d'inscription", image: "https://placehold.co/300x180/00cec9/eee?text=Register" },
  recoverPasswordForm: { label: "Recover Password", desc: "Formulaire de récupération de mot de passe", image: "https://placehold.co/300x180/a29bfe/eee?text=Recover+PWD" },
  filters: { label: "Filters", desc: "Barre de filtres pour le contenu", image: "https://placehold.co/300x180/55efc4/333?text=Filters" },
  gridLayout: { label: "Grid Layout", desc: "Mise en page en grille flexible", image: "https://placehold.co/300x180/dfe6e9/333?text=Grid+Layout" },
  searchPro: { label: "Search Pro", desc: "Recherche avancée avec filtres", image: "https://placehold.co/300x180/0984e3/eee?text=Search+Pro" },
  searchProStatic: { label: "Search Static", desc: "Recherche statique avec résultats pré-chargés", image: "https://placehold.co/300x180/74b9ff/333?text=Search+Static" },
  news: { label: "News", desc: "Fil d'actualités", image: "https://placehold.co/300x180/e17055/eee?text=News" },
  member: { label: "Member", desc: "Section membre / profil", image: "https://placehold.co/300x180/6c5ce7/eee?text=Member" },
  socialFeed: { label: "Social Feed", desc: "Flux de réseaux sociaux", image: "https://placehold.co/300x180/e84393/eee?text=Social+Feed" },
  eventList: { label: "Event List", desc: "Liste d'événements", image: "https://placehold.co/300x180/fdcb6e/333?text=Events" },
  agenda: { label: "Agenda", desc: "Events d'un costum : liste (onglets temporels), calendrier (mois/semaine/jour), carte et split", image: "https://placehold.co/300x180/0984e3/eee?text=Agenda" },
  productShowcase: { label: "Product Showcase", desc: "Vitrine de produits", image: "https://placehold.co/300x180/00b894/eee?text=Products" },
  breadcrumb: { label: "Breadcrumb", desc: "Fil d'Ariane de navigation", image: "https://placehold.co/300x180/b2bec3/333?text=Breadcrumb" },
  cookieConsent: { label: "Cookie Consent", desc: "Bannière de consentement cookies", image: "https://placehold.co/300x180/2d3436/eee?text=Cookie" },
  "hero-search": { label: "Hero recherche", desc: "Hero avec barre de recherche et autocomplete intégrés (pilote la liste de la page)", image: "https://placehold.co/300x180/1a1a2e/eee?text=Hero+Search" },
  "hero-parallax": { label: "Hero parallaxe", desc: "Hero plein écran à fond parallaxe, glow et badges", image: "https://placehold.co/300x180/0984e3/eee?text=Hero+Parallax" },
  "hero-quick-access": { label: "Hero accès rapide", desc: "Hero scindé avec pile de cartes d'accès rapide (portail)", image: "https://placehold.co/300x180/00b894/eee?text=Quick+Access" },
  "hero-tinted-overlay": { label: "Hero voile teinté", desc: "Hero plein écran à voile teinté et double slogan", image: "https://placehold.co/300x180/00cec9/eee?text=Tinted+Overlay" },
  "hero-entity-banner": { label: "Hero bannière entité", desc: "Bannière/logo/titre sourcés depuis l'entité Cocolight", image: "https://placehold.co/300x180/6c5ce7/eee?text=Entity+Banner" },
  "features-glass": { label: "Features glass", desc: "Grille de cartes-icônes glassmorphism (fade-in décalé)", image: "https://placehold.co/300x180/00b894/eee?text=Features+Glass" },
  "action-tiles": { label: "Tuiles d'action", desc: "Grille de grandes tuiles-boutons de navigation", image: "https://placehold.co/300x180/6c5ce7/eee?text=Action+Tiles" },
  "cta-card-grid": { label: "Grille de cartes CTA", desc: "Grille de cartes portant chacune son bouton d'action (+ stats)", image: "https://placehold.co/300x180/e17055/eee?text=CTA+Grid" },
  "cta-newsletter": { label: "CTA newsletter", desc: "Appel à l'action avec capture newsletter intégrée", image: "https://placehold.co/300x180/a29bfe/eee?text=CTA+News" },
  "expandable-actions": { label: "Actions dépliables", desc: "Cartes d'action en accordéon exclusif ouvrant des modales", image: "https://placehold.co/300x180/6c5ce7/eee?text=Expandable" },
  "data-observatory": { label: "Observatoire de données", desc: "Dashboard déclaratif : dimensions, KPI, graphiques, filtres et table pilotés par la config", image: "https://placehold.co/300x180/0984e3/eee?text=Observatory" },
};

export default SECTION_META;
